import Link from "next/link";

/**
 * Home-page callout for the /latest/ feed. Distinct visual treatment from
 * the static SectionPreview blocks because this content is regenerated by
 * the GitHub Actions cron, not by the maintainer's whitelist.
 */
export function LiveCallout() {
  return (
    <Link
      href="/latest"
      className="group block border-t border-rule py-12 transition first:border-t-0 first:pt-0"
    >
      <div className="grid grid-cols-12 gap-6">
        <div className="col-span-12 sm:col-span-4">
          <p className="eyebrow flex items-baseline gap-2">
            <span className="inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-ember" />
            Latest · 每 6 小时
          </p>
          <h2 className="display mt-4 text-[32px] text-ink sm:text-[40px]">
            AI <em>最新动态</em>
          </h2>
          <p className="mt-4 max-w-md text-[14px] leading-[1.7] text-ink-muted">
            GitHub Actions cron 每 6 小时调用抓取脚本，从 HackerNews 与 GitHub
            Search 获取 AI 相关内容与近期高 star 项目，结果写入静态 JSON 随构建
            一起部署。访客无需任何外部请求。
          </p>
        </div>
        <div className="col-span-12 sm:col-span-8">
          <ul className="divide-y divide-rule border-y border-rule">
            <li className="flex items-baseline justify-between py-4">
              <div className="flex items-baseline gap-4">
                <span className="font-serif text-[14px] tabular-nums text-ink-subtle">
                  01
                </span>
                <span className="font-serif text-[18px] text-ink transition group-hover:text-ember">
                  Hacker News · 多关键词查询 + 标题相关性筛选
                </span>
              </div>
              <span className="eyebrow text-ink-subtle">≥15 ↑</span>
            </li>
            <li className="flex items-baseline justify-between py-4">
              <div className="flex items-baseline gap-4">
                <span className="font-serif text-[14px] tabular-nums text-ink-subtle">
                  02
                </span>
                <span className="font-serif text-[18px] text-ink transition group-hover:text-ember">
                  GitHub Search · 近 60 天活跃 + ≥100 star
                </span>
              </div>
              <span className="eyebrow text-ink-subtle">5 个 topic 合并</span>
            </li>
          </ul>
          <p className="mt-6 eyebrow-strong text-ember transition group-hover:text-ink">
            Open the latest snapshot →
          </p>
        </div>
      </div>
    </Link>
  );
}
